name: CI Jobs

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number

jobs:
  format-check:
    name: Format check should pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}
      - name: Format
        run: just format-check

  lint:
    name: Lint should pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}
      - name: Lint
        run: just lint

  typecheck:
    name: Type Check should pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}
      - name: Type Check
        run: just typecheck

  test:
    name: Tests should pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}
      - name: Test
        run: just test
      - uses: paambaati/codeclimate-action@v9
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: just coverage --reporter lcov
          coverageLocations: coverage/lcov.info:lcov

  prepack:
    name: Prepack should work
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}
      - name: Prepack
        run: just prepack

  deps-audit:
    name: Dependencies audit should pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}
      - name: Audit
        run: just audit --prod
