name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * *'
  push:
    branches: [main, develop]

jobs:
  version-matrix:
    name: Node
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    uses: ./.github/workflows/ci-jobs.yaml
    secrets: inherit
    with:
      node-version: ${{ matrix.node-version }}
