name: Tests and Code Quality

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * WED'
  push:
    branches: [main]

jobs:
  format-check:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
      - run: npm install
      - name: Format
        run: just format-check

  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
      - run: npm install
      - name: Lint
        run: just lint

  typecheck:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
      - run: npm install
      - name: Type Check
        run: just typecheck

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
      - run: npm install
      - name: Test
        run: just test
      - uses: paambaati/codeclimate-action@v9
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: just coverage -r lcov
          coverageLocations: coverage/lcov.info:lcov
